server:
  port: 8090
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: ErpApplication
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  datasource:
    username: c##test
    password: test123!
    url: jdbc:oracle:thin:@choi1994.duckdns.org:1521:ee
    driver-class-name: oracle.jdbc.OracleDriver

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: project.onepoint.erp
  mapper-locations: classpath:/mapper/*.xml
