server:
  port: 8090
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: ErpApplication
  devtools:
    livereload:
      enabled: true
    remote:
      restart:
        enabled: true
  datasource:
    username: choi
    password: choi123!
    url: jdbc:oracle:thin:@choi1994.duckdns.org:9999:ee
    driver-class-name: oracle.jdbc.OracleDriver
  redis:
    port: 6379
    host: choi1994.duckdns.org
    password: 1234

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: project.onepoint.erp
  mapper-locations: classpath:/mapper/*.xml
